name: Bun NPM Package Publish
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile

      - name: Publish package on NPM 📦
        run: echo "Hi $NODE_AUTH_TOKEN Hi" && bun run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

# on:
#   release:
#     types: [created]